### ISSUE TITLE
remove old code: NWB web GUI should take json schema, not create it

### ISSUE THREAD

**Issue by bendichter** [catalystneuro/nwb-web-gui#25]
I see you are using `get_schema_from_hdmf_class` to create the form. This function will be used within NWB-conversion-tools, not in this repo. This package should just take and render whatever json schema it receives instead of automatically deriving a json from an hdmf class

https://github.com/catalystneuro/nwb-web-gui/blob/0a4dd3d1629077d429f33cd5c3ee85311e00c3ef/nwb_web_gui/dashapps/utils/utils.py#L31

**Comment by luiztauffer** [comment]
yes, that's old code, will be removed soon
