### ISSUE TITLE
add conversion_options form

### ISSUE THREAD

**Issue by luiztauffer** [catalystneuro/nwb-web-gui#43]
- [x] Conversion options forms added, just above the run conversion panel
- [x] Check if data is properly read and conversion options passed correctly to Converter.run_conversion()

`conversion_options` have a schema similar to `source_data`, with DataInterfaces keys as properties. So it should look like the first forms in the converter page of the gui.
An example of conversion_options data, composed of boolean options (other types are possible as well):

```
conversion_options = dict(
    EcephysInterface=dict(
        add_ecephys_raw=True,
        add_ecephys_processed=True,
        add_ecephys_spiking=True
    ),
    OphysInterface=dict(
        add_ophys_processed=True,
        add_ophys_raw=True,
        link_ophys_raw=False,
    )
)
```

Since this will be used exclusively for `NWBConverter.run_conversion()`, I think this should go below the metadata forms, where now we have the run conversion button and panel. 
@bendichter what do you think?

@vinicvaz this should be straightforward to implement, pretty much the same way we're doing the other forms: the NWBConverter class has a method `get_conversion_options_schema()` that will return the schema. We should make sure to read data from it at the moment the user clicks run conversion

**Comment by bendichter** [comment]
@luiztauffer sounds good to me.
