### ISSUE TITLE
Validate user sent data with schema

### ISSUE THREAD

**Issue by luiztauffer** [catalystneuro/nwb-web-gui#9]
Validate user sent data with schema

**Comment by luiztauffer** [comment]
since data and schema will always be produced by the converter, maybe the basic converter should have a method for data validation, inherited by all converters, instead of this being performed at the GUI side?
@bendichter @CodyCBakerPhD @alejoe91

**Comment by bendichter** [comment]
we're just going to use https://python-jsonschema.readthedocs.io/en/stable/. I don't think it would be that useful to make this a method of NWBConverter, since it would not require any internal attributes of that class
